### ISSUE TITLE
Neverending job when running validate_gsr_model workflow

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/primed-file-checks#11]
A PRIMED investigator was trying to run the `validate_gsr_model` workflow, and the job ran for ~1 hour. When we checked, it looked like it was stuck in the "import" step with the "gsr_file" table. (`avtables::import_tables` kept printing the status "Upserting").

@mconomos and I noticed that the gsr_file table had two rows with the same analysis_id because the user had first run the workflow with a test gsr file, and then reran it with the full gsr file. Both workflow runs used the same analysis file, so the analysis_id did not change. When we looked at the data tables, there were two rows in the gsr_files table with the same analysis_id.

We exported the data tables here:
`/projects/primed/analysts/amstilp/gsr_workflow_bug`

We ended up killing the job, deleting the data tables, and trying again.

**Comment by smgogarten** [comment]
I think this is an AnVIL problem; sometimes an import just gets stuck and doesn’t succeed or fail for a long time. Anecdotally, it seems to happen more often when the table already exists and rows are being appended.

**Comment by mconomos** [comment]
@smgogarten based on the log, I didn't think it was stuck, rather it seemed like it was stuck in a never ending loop that was going back and forth between two tasks. Or are you saying that it was getting stuck so it kept trying over and over again?

**Comment by smgogarten** [comment]
The workflow issued two commands: 1) import the analysis table, 2) import the gsr_file table. These are both executed asynchronously (to avoid the timeouts we used to see), so the workflow then enters a loop of checking the status of the jobs and will exit when all jobs have either succeeded or failed. In this case, one job succeeded (status=Done), but the other just kept saying it was in progress (status=Upserting). This is the result of something going wrong on the AnVIL side.

I think what is needed here is a timeout feature on the workflow side - if it hasn't succeeded after some amount of time (an hour?) it's stuck and the workflow should fail.

**Comment by mconomos** [comment]
Got it. Thanks for the explanation. A timeout feature seems like a good idea.

**Comment by smgogarten** [comment]
Fixed in https://github.com/UW-GAC/AnvilDataModels/issues/26
